meals/urls.py
from django.urls import path
from . import views

app_name = 'meals'

urlpatterns = [
    path('', views.meal_list, name='meal_list'),
    path('<slug:slug>', views.meal_detail, name='meal_detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls', namespace='meals')),
    path('reserve_table/', include('reservation.urls', namespace='reservation'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('', views.reserve_table, name='reserve_table')
]

meals/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Meals(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preparation_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True, null=True)


    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meals, self).save(*args, **kwargs)


    class Meta:
        verbose_name = 'meal'
        verbose_name_plural = 'meals'
        

    def __str__(self):
        return  self.name

reservation/models.py
from django.db import models

# Create your models here.

class Reservation(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    phone = models.IntegerField()
    number_of_persons = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()


    def __str__(self):
        return self.name

reservation/forms.py
from django import forms
from .models import Reservation

class ReserveTableForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

meals/views.py
from django.shortcuts import render
from .models import Meals

# Create your views here.

def meal_list(request):
    meal_list = Meals.objects.all()
    context = {'meal_list' : meal_list}
    return render(request, 'Meals/list.html', context)


def meal_detail(request, slug):
    meal_detail = Meals.objects.get(slug=slug)
    context = {'meal_detail': meal_detail}
    return render(request, 'Meals/detail.html', context)

reservation/views.py
from .models import Reservation
from django.shortcuts import render
from .forms import ReserveTableForm
from reservation.models import Reservation

# Create your views here.

def reserve_table(request):
    reserve_form = ReserveTableForm()

    if request.method == 'POST':
        reserve_form = ReserveTableForm(request.POST)

        if reserve_form.is_valid():
            reserve_form.save()

    context = {'form': reserve_form}

    return render(request, 'Reservation/reservation.html', context)

meals/templates/Meals/detail.html
{% extends 'base.html' %}

{% block body %}


  <!-- About Section -->
  <section id="about">
    <div class="about container">
      <div class="col-left">
        <div class="about-img">
          <img src="{{meal_detail.image.url}}" alt="img">
        </div>
      </div>
      <div class="col-right">
        <h1 class="section-title">{{meal_detail.name}}</span></h1>
        <p>{{meal_detail.description}}</p>
        <p>People: {{meal_detail.people}}</p>
        <p>Preparation Time: {{meal_detail.preparation_time}} minutes</p>
        <h2>Price: {{meal_detail.price}}&euro;</h2>
      </div>
    </div>
  </section>
  <!-- End About Section -->


{% endblock body %}

meals/templates/Meals/list.html
{% extends 'base.html' %}

{% block body %}


  <!-- Service Section -->
  <section id="services">
    <div class="services container">
      <div class="service-top">
        <h1 class="section-title">Menu List</h1>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum deleniti maiores pariatur assumenda quas magni et, doloribus quod voluptate quasi molestiae magnam officiis dolorum, dolor provident atque molestias voluptatum explicabo!</p>
      </div>
      <div class="service-bottom">

		{% for meal in meal_list %}
			<div class="service-item">
			<h2><a href="{% url 'meals:meal_detail' meal.slug %}">{{meal.name}}</a></h2>
			<p>{{meal.description}}</p>
			<h2>{{meal.price}}&euro;</h2>	
			</div>
		{% endfor %}

      </div>
    </div>
  </section>
  <!-- End Service Section -->


{% endblock body %}

reservation/templates/Reservation/reservation.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block body %}


  <!-- About Section -->
  <section id="reservation">
    <div class="about container"> 
      
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="btn btn-primary">Reserve a table</button>
        {% endbuttons %}
      </form>

    </div>
  </section>
  <!-- End About Section -->


{% endblock body %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'site_static/style.css' %}">
  <title>Restaurant</title>
</head>
<body>
  <!-- Header -->
  <section id="header">
    <div class="header container">
      <div class="nav-bar">
        <div class="brand">
          <a href="#hero"><h1><span>Restaurant</span></h1></a>
        </div>
        <div class="nav-list">
          <div class="hamburger"><div class="bar"></div></div>
          <ul>
            <li><a href="#hero" data-after="Home">Home</a></li>
            <li><a href="#menu" data-after="Service">Menu</a></li>
            <li><a href="#reservation" data-after="Projects">Reservation</a></li>
            <li><a href="#about" data-after="About">About</a></li>
            <li><a href="#contact" data-after="Contact">Contact</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!-- End Header -->


  <!-- Hero Section  -->
  <section id="hero">
    <div class="hero container">
      <div>
        <h1>Welcome, <span></span></h1>
        <h1>to the <span></span></h1>
        <h1>Restaurant <span></span></h1>
        <a href="#menu" type="button" class="cta">Menu</a>
      </div>
    </div>
  </section>
  <!-- End Hero Section  -->


  {% block body %}

  {% endblock body %}


  <!-- Footer -->
  <section id="footer">
    <div class="footer container">
      <div class="brand"><h1>Restaurant</h1></div>
      <h2>Your Complete Web Solution</h2>
      <div class="social-icon">
        <div class="social-item">
          <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/facebook-new.png"/></a>
        </div>
        <div class="social-item">
          <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/instagram-new.png"/></a>
        </div>
        <div class="social-item">
          <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/twitter.png"/></a>
        </div>
        <div class="social-item">
          <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/behance.png"/></a>
        </div>
      </div>
      <p>Copyright ©2021 Arfan Template. All rights reserved</p>
    </div>
  </section>
  <!-- End Footer -->
  <script src="{% static 'site_static/js/app.js' %}"></script>
</body>
</html>